name: Package

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@latest
        with:
            version: '1.4'

      - name: Install necessary libs
        run: sudo apt-get install libglu1

      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Set up git user.name
        run: git config --global user.name "Shi Pengcheng"

      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add("BinaryBuilder")'

      - name: Package Official SDK
        env:
          GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
          BINARYBUILDER_AUTOMATIC_APPLE: true
        run: julia build_tarballs.jl --deploy=shipengcheng1230/Gmsh_jll.jl
